#cloud-config
package_update: true
packages:
  - iperf
  - mysql-server

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDg8Nyku3bipbAqoTkz9g8k6a+UBfE6OeZMCHSmWZKRDZIbbRwXZIq/N9daCTyKn5uMlUQGKPgjcYpeLDalU4yDSIDllW71EyB3uxAHwArD3Mzx/gRP0xiybCLG43gpw7kQ/Cnt2hV8JRsP52OQwafRR2FclsmQRH6BN9/AreUftCRE/wj8MPAGGzdcxJryAeHELlHLCEFeIkCXCfJplQPYnUXmcjD1KeJ9kSSd7mEtFnXxwg3j4nmdSNu5w3eZ74mlG6HudnHG9MxPW5GVs0jEOXwJxn8owmoKChcuZ7aiQyp8mG9KLjGRoOJw7eVb0jVvkrAnNEEht+aebND2ms6n Generated-by-Nova
    passwd: twcam$2023*

runcmd:
  - mkfs.ext4 /dev/vdb
  - mkdir -p /mnt/mysql_data
  - echo '/dev/vdb /mnt/mysql_data ext4 defaults 0 0' >> /etc/fstab
  - mount -a
