#cloud-config
password: <PASSWORD>
chpassword:
	expire: false
	ssh_pwauth: true
packages:
  - iperf
  - tomcat9
mounts:
  - [ /dev/vdb, /var/lib/tomcat9, ext4, "defaults", 0, 2 ]
runcmd:
  - [ mkfs.ext4, /dev/vdb ]
  - [ mkdir, -p, /var/lib/tomcat9 ]
  - [ mount, /dev/vdb, /var/lib/tomcat9 ]

